routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('/invoices' ,'App\Http\Controllers\InvoicesController');
Route::resource('/bonEntrees' ,'App\Http\Controllers\BonEntreeController');
Route::resource('/bonSorties' ,'App\Http\Controllers\BonSortieController');
Route::resource('/categories' ,'App\Http\Controllers\CategoriesController');
Route::resource('/articles' ,'App\Http\Controllers\ArticlesController');
Route::get('/categorie/{id}' ,'App\Http\Controllers\BonEntreeController@getproducts');
Route::resource('InvoiceAttachments', 'App\Http\Controllers\Invoices_AttachmentController');
Route::get('/details/{id}' ,'App\Http\Controllers\Invoices_DetailsController@show')->name('details');
Route::get('download/{invoice_number}/{file_name}', 'App\Http\Controllers\Invoices_DetailsController@get_file');

Route::get('/detail/{reference}' ,'App\Http\Controllers\ArticlesController@detail')->name('detail');
Route::get('print/{id}', 'App\Http\Controllers\BonSortieController@print')->name('print');
Route::get('MarkAsRead_all' , 'App\Http\Controllers\ArticlesController@MarkAsRead_all')->name('MarkAsRead_all');

Route::get('View_file/{invoice_number}/{file_name}', 'App\Http\Controllers\Invoices_DetailsController@open_file');

Route::post('delete_file', 'App\Http\Controllers\Invoices_DetailsController@destroy')->name('delete_file');
Route::get('status_show/{id}', 'App\Http\Controllers\InvoicesController@show')->name('status_show');
Route::post('status_show/{id}', 'App\Http\Controllers\InvoicesController@status_update')->name('status_update');

Route::get('paid', 'App\Http\Controllers\InvoicesController@paid');
Route::get('unpaid', 'App\Http\Controllers\InvoicesController@unpaid');
Route::get('partial', 'App\Http\Controllers\InvoicesController@partial');

Route::resource('/archive' ,'App\Http\Controllers\ArchiveController');
// Route::get('print/{id}', 'App\Http\Controllers\InvoicesController@print')->name('print');
Route::get('export_invoices', 'App\Http\Controllers\InvoicesController@export');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles','App\Http\Controllers\RoleController');
    Route::resource('users','App\Http\Controllers\UserController');
});

Route::get('invoices_report', 'App\Http\Controllers\Invoices_Reports@index');
Route::post('Search_invoices', 'App\Http\Controllers\Invoices_Reports@Search_invoices');

Route::get('customers_report', 'App\Http\Controllers\Customers_Report@index')->name("customers_report");
Route::post('Search_customers', 'App\Http\Controllers\Customers_Report@Search_customers');

Route::get('/{page}', 'App\Http\Controllers\AdminController@index');

app/Models/BonEntree.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class BonEntree extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'bon_number',
        'bon_date',
        'article',
        'categorie_id',
        'quantite',
        'prix_unitaire',
        'prix_total',
        'created_by',
        'received_by'
    ];

    public function categorie(){
        return $this->belongsTo('App\Models\Categorie');
    }
}

app/Http/Controllers/BonEntreeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use App\Models\BonEntree;
use App\Models\Categorie;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class BonEntreeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $bonEntrees = BonEntree::all();
        return view('bonEntrees.listBon',compact('bonEntrees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Categorie::all();
        return view('bonEntrees.creeBon',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        

        // $stock = Article::select('stock')->where('reference', $request->article)->get();
        // dd($stock);
       // dump($request);
        BonEntree::create([
            'bon_number' => $request->bon_number,
            'bon_date' => $request->bon_date,
            'article' => $request->article,
            'categorie_id' => $request->categorie,
            'quantite' => $request->quantite,
            'prix_unitaire' => $request->prix_unitaire,
            'prix_total' => $request->prix_total,
            'created_by' => $request->created_by = Auth::user()->name,
            'received_by' => $request->received_by
        ]);

        $stock = DB::table('articles')->select('stock')->where('reference', $request->article)->value('stock');
        $stock += $request->quantite;
        DB::table('articles')->where('reference', $request->article)->update(['stock' => $stock]);

        

        // $invoice_id = Invoice::latest()->first()->id;
        // Invoices_Details::create([
        //     'id_Invoice' => $invoice_id,
        //     'invoice_number' => $request->invoice_number,
        //     'article' => $request->article,
        //     'categorie' => $request->categorie,
        //     'Status' => 'غير مدفوعة',
        //     'Value_Status' => 2,
        //     'note' => $request->note,
        //     'user' => (Auth::user()->name),
        // ]);

        // if ($request->hasFile('pic')) {

        //     $invoice_id = Invoice::latest()->first()->id;
        //     $image = $request->file('pic');
        //     $file_name = $image->getClientOriginalName();
        //     $invoice_number = $request->invoice_number;

        //     $attachments = new Invoices_Attachment();
        //     $attachments->file_name = $file_name;
        //     $attachments->invoice_number = $invoice_number;
        //     $attachments->Created_by = Auth::user()->name;
        //     $attachments->invoice_id = $invoice_id;
        //     $attachments->save();

        //     // move pic
        //     $imageName = $request->pic->getClientOriginalName();
        //     $request->pic->move(public_path('Attachments/' . $invoice_number), $imageName);
        // }

         
        // $user = User::first();
        // Notification::send($user, new AddInvoice($invoice_id));


        
        session()->flash('Add', 'Bon crée avec succés');
        //return back();
        return redirect()->route('bonEntrees.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\BonEntree  $bonEntree
     * @return \Illuminate\Http\Response
     */
    public function show(BonEntree $bonEntree)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\BonEntree  $bonEntree
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $bonEntrees = BonEntree::where('id', $id)->first();
        $categories = Categorie::all();
        return view('bonEntrees.editBon', compact('bonEntrees','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\BonEntree  $bonEntree
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, BonEntree $bonEntree)
    {
        //dd($request->bonEntree_id);
        $bonEntree = BonEntree::findOrFail($request->bonEntree_id);
        $bonEntree->update([
            'bon_number' => $request->bon_number,
            'bon_date' => $request->bon_date,
            'article' => $request->article,
            'categorie_id' => $request->categorie,
            'quantite' => $request->quantite,
            'prix_unitaire' => $request->prix_unitaire,
            'prix_total' => $request->prix_total,
            'created_by' => $request->created_by = Auth::user()->name,
            'received_by' => $request->received_by,

        ]);

        //dd($bonEntree);

        session()->flash('edit', 'Bon modifier avec success');
        //return back();
        return redirect()->route('bonEntrees.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\BonEntree  $bonEntree
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {

        //dd($request);

        $id =  $request->bon_id;
        $bonEntree = BonEntree::where('id' , $id)->first();
        $page_id = $request->page_id;
        if(!$page_id == 2){
        
            $bonEntree->forceDelete();
            session()->flash('success', 'suppression effectuée ');
            return redirect()->route('bonEntrees.index');

        }else {
            $bonEntree->delete();
            session()->flash('success', 'archivage effectuée');
            return redirect()->route('bonEntrees.index');
        } 

    }

    public function getproducts($id)
    {
        $articles = DB::table("articles")->where("categorie_id", $id)->pluck("reference", "id");
        return json_encode($articles);
    }
}

resources/views/bonEntrees/listBon.blade.php
@extends('layouts.master')
@section('css')
    <!-- Internal Data table css -->
    <link href="{{ URL::asset('assets/plugins/datatable/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet" />
    <link href="{{ URL::asset('assets/plugins/datatable/css/buttons.bootstrap4.min.css') }}" rel="stylesheet">
    <link href="{{ URL::asset('assets/plugins/datatable/css/responsive.bootstrap4.min.css') }}" rel="stylesheet" />
    <link href="{{ URL::asset('assets/plugins/datatable/css/jquery.dataTables.min.css') }}" rel="stylesheet">
    <link href="{{ URL::asset('assets/plugins/datatable/css/responsive.dataTables.min.css') }}" rel="stylesheet">
    <link href="{{ URL::asset('assets/plugins/select2/css/select2.min.css') }}" rel="stylesheet">
    <!--Internal   Notify -->
    <link href="{{URL::asset('assets/plugins/notify/css/notifIt.css')}}" rel="stylesheet"/>
@endsection
@section('page-header')
    <!-- breadcrumb -->
    <div class="breadcrumb-header justify-content-between">
        <div class="my-auto">
            <div class="d-flex">
                <h4 class="content-title mb-0 my-auto">Bon d'Entrees</h4><span class="text-muted mt-1 tx-13 mr-2 mb-0">/ Tous les
                    Bon d'Entrees</span>
            </div>
        </div>

    </div>
    <!-- breadcrumb -->
@endsection
@section('content')
    <!-- row -->
    <div class="row">
        <div class="col-xl-12">
            <!-- notification of deleteing -->
            @if (session()->has('success'))
                <script>
                    window.onload = function(){
                        notif({
                            msg : "Suppréssion avec succés",
                            type : "success"
                        })
                    }
                </script>
            @endif
            @if (session()->has('paiment'))
                <script>
                    window.onload = function(){
                        notif({
                            msg : "Operation Done Successfully ",
                            type : "success"
                        })
                    }
                </script>
            @endif
            <div class="card mg-b-20">
                <div class="card-header pb-0">
                    {{-- @can('ajouter bon') --}}
                    <a href="{{route('bonEntrees.create')}}" class="modal-effect btn btn-sm btn-primary" style="color:white"><i
                            class="fas fa-plus"></i>&nbsp; Ajouter un Bon </a>
                    {{-- @endcan --}}
                    {{-- @can('export EXCEL') --}}
                    {{-- <a href="export_invoices" class="modal-effect btn btn-sm btn-success" style="color:white"><i
                        class="fas fa-file-download"></i>&nbsp; Export Excel
                     </a> --}}
                    {{-- @endcan --}}
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="example1" class="table key-buttons text-md-nowrap" data-page-length='10'style="text-align: center">
                            <thead>
                                <tr>
                                    <th class="border-bottom-0">#</th>
                                    <th class="border-bottom-0">Numéro du Bon</th>
                                    <th class="border-bottom-0">Date d'Entrée</th>
                                    <th class="border-bottom-0">Article</th>
                                    <th class="border-bottom-0">Categorie</th>
                                    <th class="border-bottom-0">Quantité</th>
                                    <th class="border-bottom-0">Prix Unitaire</th>
                                    <th class="border-bottom-0">Prix Total</th>
                                    <th class="border-bottom-0">Receptionné Par</th>
                                    <th class="border-bottom-0">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            @if (empty($bonEntrees))
                                <th class="border-bottom-0 text-bold"> Aucun bon n'est trouvé !!</th>
                            @else
                                @php
                                $i = 0 ;
                                @endphp
                                @foreach ($bonEntrees as $bonEntree)
                                    @php
                                    $i++;
                                    @endphp
                                    <tr class="text-center">
                                        <td>{{ $bonEntree->id }}</td>
                                        <td>{{$bonEntree->bon_number}}</td>
                                        <td>{{$bonEntree->bon_date}}</td>
                                        <td>{{$bonEntree->article}}</td>
										{{-- <td><a
											href="{{ url('details') }}/{{ $invoice->id }}">{{ $invoice->categorie->categorie_name }}</a>
										</td> --}}
                                        <td>{{$bonEntree->categorie->categorie_name}}</td>
                                        <td>{{$bonEntree->quantite}}</td>
                                        <td>{{$bonEntree->prix_unitaire}}</td>
                                        <td>{{$bonEntree->prix_total}}</td>
                                        <td>{{$bonEntree->received_by}}</td>
                                        <td>	
											<div class="dropdown">
												<button aria-expanded="false" aria-haspopup="true" class="btn btn-sm btn-primary"
												data-toggle="dropdown" id="dropdownMenuButton" type="button">Menu<i class="fas fa-caret-down ml-1"></i></button>
												<div  class="dropdown-menu tx-md-10">
                                                    {{-- @can('modifie bon') --}}
													<a class="dropdown-item text-success btn-sm" 
                                                        href="{{route('bonEntrees.edit',$bonEntree->id)}}">Modifier</a>
                                                    {{-- @endcan --}}
                                                    {{-- @can('supprime bon') --}}
                                                    <a class="dropdown-item text-info btn-sm"
                                                        data-bon_id="{{$bonEntree->id}}"
                                                        data-toggle="modal"
                                                        data-target="#archive_bon"
                                                        href="#">Archive</a>
                                                    {{-- @endcan --}}
                                                    {{-- @can('archive bon') --}}
                                                    <a class="dropdown-item text-danger btn-sm"
                                                        data-bon_id="{{ $bonEntree->id }}"
                                                        data-toggle="modal"
                                                        data-target="#delete_bon"
                                                        href="#">Delete</a>
                                                    {{-- @endcan --}}
                                                    {{-- @can('print bon') --}}
                                                    <a class="dropdown-item text-primary btn-sm" 
                                                        href="{{route('print',$bonEntree->id)}}">Print</a>
                                                    {{-- @endcan --}}
												</div>
											</div>
										</td>                               
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- row closed -->
    <!-- Deleteing Model-->
    <div class="modal fade" id="delete_bon" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">حذف المرفق</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('bonEntrees.destroy',"test")}}" method="post">
                @method('DELETE')
                {{ csrf_field() }}
                <div class="modal-body">
                    <p class="text-center">
                    <h6 style="color:red"> هل انت متاكد من عملية حذف المرفق ؟</h6>
                    </p>
                    
                    <input type="text" name="bon_id" id="bon_id" value="">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">الغاء</button>
                    <button type="submit" class="btn btn-danger">تاكيد</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- End Deleteing Model -->
<!-- Archiving Model-->
<div class="modal fade" id="archive_bon" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">حذف المرفق</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('bonEntrees.destroy',"test")}}" method="post">
                @method('DELETE')
                {{ csrf_field() }}
                <div class="modal-body">
                    <p class="text-center">
                    <h6 style="color:red"> هل انت متاكد من عملية حذف المرفق ؟</h6>
                    </p>
                    <input type="text" name="page_id" id="page_id" value="2">
                    <input type="text" name="bon_id" id="bon_id" value="">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">الغاء</button>
                    <button type="submit" class="btn btn-danger">تاكيد</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- End Archiing Model -->
</div>
<!-- Container closed -->
</div>
<!-- main-content closed -->
@endsection
@section('js')
    <!-- Internal Data tables -->
    <script src="{{ URL::asset('assets/plugins/datatable/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/dataTables.dataTables.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/responsive.dataTables.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/jquery.dataTables.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/dataTables.bootstrap4.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/buttons.bootstrap4.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/jszip.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/pdfmake.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/vfs_fonts.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/buttons.html5.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/buttons.print.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/buttons.colVis.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/responsive.bootstrap4.min.js') }}"></script>
    <!--Internal  Datatable js -->
    <script src="{{ URL::asset('assets/js/table-data.js') }}"></script>
    <!--Internal  Notify js -->
    <script src="{{URL::asset('assets/plugins/notify/js/notifIt.js')}}"></script>
    <script src="{{URL::asset('assets/plugins/notify/js/notifit-custom.js')}}"></script>




<script>
$('#delete_bon').on('show.bs.modal', function(event) {
    var button = $(event.relatedTarget)
    var bon_id = button.data('bon_id')
    var modal = $(this)
    modal.find('.modal-body #bon_id').val(bon_id);
})
</script>
<script>
$('#archive_bon').on('show.bs.modal', function(event) {
    var button = $(event.relatedTarget)
    var bon_id = button.data('bon_id')
    var modal = $(this)
    modal.find('.modal-body #bon_id').val(bon_id);
})
</script>
@endsection