routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('/invoices' ,'App\Http\Controllers\InvoicesController');
Route::resource('/bonEntrees' ,'App\Http\Controllers\BonEntreeController');
Route::resource('/bonSorties' ,'App\Http\Controllers\BonSortieController');
Route::resource('/categories' ,'App\Http\Controllers\CategoriesController');
Route::resource('/articles' ,'App\Http\Controllers\ArticlesController');
Route::get('/categorie/{id}' ,'App\Http\Controllers\BonEntreeController@getproducts');
Route::resource('InvoiceAttachments', 'App\Http\Controllers\Invoices_AttachmentController');
Route::get('/details/{id}' ,'App\Http\Controllers\Invoices_DetailsController@show')->name('details');
Route::get('download/{invoice_number}/{file_name}', 'App\Http\Controllers\Invoices_DetailsController@get_file');

Route::get('/detail/{reference}' ,'App\Http\Controllers\ArticlesController@detail')->name('detail');
Route::get('print/{id}', 'App\Http\Controllers\BonSortieController@print')->name('print');
Route::get('MarkAsRead_all' , 'App\Http\Controllers\ArticlesController@MarkAsRead_all')->name('MarkAsRead_all');

Route::get('View_file/{invoice_number}/{file_name}', 'App\Http\Controllers\Invoices_DetailsController@open_file');

Route::post('delete_file', 'App\Http\Controllers\Invoices_DetailsController@destroy')->name('delete_file');
Route::get('status_show/{id}', 'App\Http\Controllers\InvoicesController@show')->name('status_show');
Route::post('status_show/{id}', 'App\Http\Controllers\InvoicesController@status_update')->name('status_update');

Route::get('paid', 'App\Http\Controllers\InvoicesController@paid');
Route::get('unpaid', 'App\Http\Controllers\InvoicesController@unpaid');
Route::get('partial', 'App\Http\Controllers\InvoicesController@partial');

Route::resource('/archive' ,'App\Http\Controllers\ArchiveController');
// Route::get('print/{id}', 'App\Http\Controllers\InvoicesController@print')->name('print');
Route::get('export_invoices', 'App\Http\Controllers\InvoicesController@export');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles','App\Http\Controllers\RoleController');
    Route::resource('users','App\Http\Controllers\UserController');
});

Route::get('invoices_report', 'App\Http\Controllers\Invoices_Reports@index');
Route::post('Search_invoices', 'App\Http\Controllers\Invoices_Reports@Search_invoices');

Route::get('customers_report', 'App\Http\Controllers\Customers_Report@index')->name("customers_report");
Route::post('Search_customers', 'App\Http\Controllers\Customers_Report@Search_customers');

Route::get('/{page}', 'App\Http\Controllers\AdminController@index');

resources/views/bonSorties/creeBon.blade.php
@extends('layouts.master')
@section('css')
    <!--- Internal Select2 css-->
    <link href="{{ URL::asset('assets/plugins/select2/css/select2.min.css') }}" rel="stylesheet">
    <!---Internal Fileupload css-->
    <link href="{{ URL::asset('assets/plugins/fileuploads/css/fileupload.css') }}" rel="stylesheet" type="text/css" />
    <!---Internal Fancy uploader css-->
    <link href="{{ URL::asset('assets/plugins/fancyuploder/fancy_fileupload.css') }}" rel="stylesheet" />
    <!--Internal Sumoselect css-->
    <link rel="stylesheet" href="{{ URL::asset('assets/plugins/sumoselect/sumoselect-rtl.css') }}">
    <!--Internal  TelephoneInput css-->
    <link rel="stylesheet" href="{{ URL::asset('assets/plugins/telephoneinput/telephoneinput-rtl.css') }}">
@endsection
@section('title')
     Ajouter un Bon de Sortie
@stop

@section('page-header')
    <!-- breadcrumb -->
    <div class="breadcrumb-header justify-content-between">
        <div class="my-auto">
            <div class="d-flex">
                <h4 class="content-title mb-0 my-auto">Les Bons de Sortie</h4><span class="text-muted mt-1 tx-13 mr-2 mb-0">
                     Ajouter un Bon de Sortie</span>
            </div>
        </div>
    </div>
    <!-- breadcrumb -->
@endsection
@section('content')

    @if (session()->has('Add'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>{{ session()->get('Add') }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif

    <!-- row -->
    <div class="row">

        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-body">
                 
                    <form action="{{ route('bonSorties.store') }}" method="post" enctype="multipart/form-data"
                        autocomplete="off">
                        {{ csrf_field() }}
                        {{-- 1 --}}
                        <div class="row">
                            <div class="col">
                                <label for="inputName" class="control-label">Nom de Client</label>
                                <input type="text" class="form-control" id="inputName" name="client_name"
                                    title="entrée le nom de client" required>
                            </div>

                            <div class="col">
                                <label>Adresse de Client</label>
                                <input class="form-control" name="client_adress" placeholder="Adresss"
                                    type="text" required>
                            </div>
                            <div class="col">
                                <label>N° de TELE de Client :</label>
                                <input class="form-control" name="client_mobile" placeholder="+212..."
                                    type="text" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <label for="inputName" class="control-label">Numéro du Bon</label>
                                <input type="text" class="form-control" id="inputName" name="bon_number"
                                    title="entrée le numéro de votre bon" required>
                            </div>

                            <div class="col">
                                <label>Date de sortie du Bon</label>
                                <input class="form-control fc-datepicker" name="bon_date" placeholder="YYYY-MM-DD"
                                    type="text" value="{{ date('Y-m-d') }}" required>
                            </div>

                        </div>

                        {{-- 2 --}}
                        <div class="row">
                            <div class="col">
                                <label for="inputName" class="control-label">Categorie</label>
                                <select name="categorie" class="form-control SlectBox" onclick="console.log($(this).val())"
                                    onchange="console.log('change is firing')">
                                    <!--placeholder-->
                                    <option value="" selected disabled>Choisit Catégorie</option>
                                    @foreach ($categories as $categorie)
                                        <option value="{{ $categorie->id }}"> {{ $categorie->categorie_name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="col">
                                <label for="inputName" class="control-label">Article</label>
                                <select id="article" name="article" class="form-control">
                                </select>
                            </div>

                        </div>


                        {{-- 3 --}}

                        <div class="row">

                            <div class="col">
                                <label for="inputName" class="control-label"> Quantité</label>
                                <input type="text" class="form-control form-control-lg" id="quantite"
                                    name="quantite" title="Entrer la Quantité"
                                    oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');"
                                    required>
                            </div>

                            <div class="col">
                                <label for="inputName" class="control-label">Prix Unitaire</label>
                                <input type="text" class="form-control form-control-lg" id="prix_unitaire" name="prix_unitaire"
                                    title="Entrer le prix unitaire"
                                    oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');"
                                    onchange="myFunction()"
                                    value=0 required>
                            </div>
                        </div>
                        {{-- 4 --}}

                        <div class="row">
                            <div class="col">
                                <label for="inputName" class="control-label"> Prix Total</label>
                                <input type="text" class="form-control" id="prix_total" name="prix_total" readonly>
                            </div>
                        </div>

                        <div class="d-flex justify-content-center mt-2">
                            <button type="submit" class="btn btn-primary">Sauvegarder</button>
                        </div>


                    </form>
                </div>
            </div>
        </div>
    </div>

    </div>

    <!-- row closed -->
    </div>
    <!-- Container closed -->
    </div>
    <!-- main-content closed -->
@endsection
@section('js')
    <!-- Internal Select2 js-->
    <script src="{{ URL::asset('assets/plugins/select2/js/select2.min.js') }}"></script>
    <!--Internal Fileuploads js-->
    <script src="{{ URL::asset('assets/plugins/fileuploads/js/fileupload.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/fileuploads/js/file-upload.js') }}"></script>
    <!--Internal Fancy uploader js-->
    <script src="{{ URL::asset('assets/plugins/fancyuploder/jquery.ui.widget.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/fancyuploder/jquery.fileupload.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/fancyuploder/jquery.iframe-transport.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/fancyuploder/jquery.fancy-fileupload.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/fancyuploder/fancy-uploader.js') }}"></script>
    <!--Internal  Form-elements js-->
    <script src="{{ URL::asset('assets/js/advanced-form-elements.js') }}"></script>
    <script src="{{ URL::asset('assets/js/select2.js') }}"></script>
    <!--Internal Sumoselect js-->
    <script src="{{ URL::asset('assets/plugins/sumoselect/jquery.sumoselect.js') }}"></script>
    <!--Internal  Datepicker js -->
    <script src="{{ URL::asset('assets/plugins/jquery-ui/ui/widgets/datepicker.js') }}"></script>
    <!--Internal  jquery.maskedinput js -->
    <script src="{{ URL::asset('assets/plugins/jquery.maskedinput/jquery.maskedinput.js') }}"></script>
    <!--Internal  spectrum-colorpicker js -->
    <script src="{{ URL::asset('assets/plugins/spectrum-colorpicker/spectrum.js') }}"></script>
    <!-- Internal form-elements js -->
    <script src="{{ URL::asset('assets/js/form-elements.js') }}"></script>

    <script>
        var date = $('.fc-datepicker').datepicker({
            dateFormat: 'yy-mm-dd'
        }).val();
    </script>

    <script>
        $(document).ready(function() {
            $('select[name="categorie"]').on('change', function() {
                var categorieId = $(this).val();
                if (categorieId) {
                    $.ajax({
                        url: "{{ URL::to('categorie') }}/" + categorieId,
                        type: "GET",
                        dataType: "json",
                        success: function(data) {
                            $('select[name="article"]').empty();
                            $.each(data, function(key, value) {
                                $('select[name="article"]').append('<option value="' +
                                    value + '">' + value + '</option>');
                            });
                        },
                    });
                } else {
                    console.log('AJAX load did not work');
                }
            });
        });
    </script>

    <script>
        function myFunction() {
            var quantite = parseFloat(document.getElementById("quantite").value);
            var prix_unitaire = parseFloat(document.getElementById("prix_unitaire").value);
            var prix_total = parseFloat(document.getElementById("prix_total").value);
            if (typeof quantite === 'undefined' || !quantite) {
                alert('entrée la quantité !');
            } else {
                sumq = parseFloat(quantite * prix_unitaire).toFixed(2);
                document.getElementById("prix_total").value = sumq;
            }
        }
    </script>


@endsection

resources/views/bonSorties/listBon.blade.php
@extends('layouts.master')
@section('css')
    <!-- Internal Data table css -->
    <link href="{{ URL::asset('assets/plugins/datatable/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet" />
    <link href="{{ URL::asset('assets/plugins/datatable/css/buttons.bootstrap4.min.css') }}" rel="stylesheet">
    <link href="{{ URL::asset('assets/plugins/datatable/css/responsive.bootstrap4.min.css') }}" rel="stylesheet" />
    <link href="{{ URL::asset('assets/plugins/datatable/css/jquery.dataTables.min.css') }}" rel="stylesheet">
    <link href="{{ URL::asset('assets/plugins/datatable/css/responsive.dataTables.min.css') }}" rel="stylesheet">
    <link href="{{ URL::asset('assets/plugins/select2/css/select2.min.css') }}" rel="stylesheet">
    <!--Internal   Notify -->
    <link href="{{URL::asset('assets/plugins/notify/css/notifIt.css')}}" rel="stylesheet"/>
@endsection
@section('page-header')
    <!-- breadcrumb -->
    <div class="breadcrumb-header justify-content-between">
        <div class="my-auto">
            <div class="d-flex">
                <h4 class="content-title mb-0 my-auto">Bon de Sortie</h4><span class="text-muted mt-1 tx-13 mr-2 mb-0">/ Tous les
                    Bon de Sortie</span>
            </div>
        </div>

    </div>
    <!-- breadcrumb -->
@endsection
@section('content')
    <!-- row -->
    <div class="row">
        <div class="col-xl-12">
            <!-- notification of deleteing -->
            @if (session()->has('success'))
                <script>
                    window.onload = function(){
                        notif({
                            msg : "Suppréssion avec succés",
                            type : "success"
                        })
                    }
                </script>
            @endif
            @if (session()->has('Add'))
                <script>
                    window.onload = function(){
                        notif({
                            msg : "Operation Done Successfully ",
                            type : "success"
                        })
                    }
                </script>
            @endif
            @if (session()->has('stock'))
                <script>
                    window.onload = function(){
                        notif({
                            msg : "Verfifié Votre Srock !!",
                            type : "success"
                        })
                    }
                </script>
            @endif
            <div class="card mg-b-20">
                <div class="card-header pb-0">
                    {{-- @can('add invoice') --}}
                    <a href="{{route('bonSorties.create')}}" class="modal-effect btn btn-sm btn-primary" style="color:white"><i
                            class="fas fa-plus"></i>&nbsp; Ajouter un Bon </a>
                    {{-- @endcan --}}
                    {{-- @can('export EXCEL') --}}
                    {{-- <a href="export_invoices" class="modal-effect btn btn-sm btn-success" style="color:white"><i
                        class="fas fa-file-download"></i>&nbsp; Export Excel 
                    </a> --}}
                    {{-- @endcan --}}
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="example1" class="table key-buttons text-md-nowrap" data-page-length='10'style="text-align: center">
                            <thead>
                                <tr>
                                    <th class="border-bottom-0">#</th>
                                    <th class="border-bottom-0">Numéro du Bon</th>
                                    <th class="border-bottom-0">Date de Sortie</th>
                                    <th class="border-bottom-0">Article</th>
                                    <th class="border-bottom-0">Categorie</th>
                                    <th class="border-bottom-0">Quantité</th>
                                    <th class="border-bottom-0">Prix Unitaire</th>
                                    <th class="border-bottom-0">Prix Total</th>
                                    <th class="border-bottom-0">Crée Par</th>
                                    <th class="border-bottom-0">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            @if (empty($bonSorties))
                                <th class="border-bottom-0 text-bold"> Aucun bon n'est trouvé !!</th>
                            @else
                                @php
                                $i = 0 ;
                                @endphp
                                @foreach ($bonSorties as $bonSortie)
                                    @php
                                    $i++;
                                    @endphp
                                    <tr class="text-center">
                                        <td>{{ $bonSortie->id }}</td>
                                        <td>{{$bonSortie->bon_number}}</td>
                                        <td>{{$bonSortie->bon_date}}</td>
                                        <td>{{$bonSortie->article}}</td>
										{{-- <td><a
											href="{{ url('details') }}/{{ $invoice->id }}">{{ $invoice->categorie->categorie_name }}</a>
										</td> --}}
                                        <td>{{$bonSortie->categorie->categorie_name}}</td>
                                        <td>{{$bonSortie->quantite}}</td>
                                        <td>{{$bonSortie->prix_unitaire}}</td>
                                        <td>{{$bonSortie->prix_total}}</td>
                                        <td>{{$bonSortie->created_by}}</td>
                                        <td>	
											<div class="dropdown">
												<button aria-expanded="false" aria-haspopup="true" class="btn btn-sm btn-primary"
												data-toggle="dropdown" id="dropdownMenuButton" type="button">Menu<i class="fas fa-caret-down ml-1"></i></button>
												<div  class="dropdown-menu tx-md-10">
                                                    {{-- @can('modifie bon') --}}
													<a class="dropdown-item text-success btn-sm" 
                                                        href="{{route('bonSorties.edit',$bonSortie->id)}}">Edit</a>
                                                    {{-- @endcan --}}
                                                    {{-- @can('supprime bon') --}}
                                                    <a class="dropdown-item text-info btn-sm"
                                                        data-bon_id="{{$bonSortie->id}}"
                                                        data-toggle="modal"
                                                        data-target="#archive_bon"
                                                        href="#">Archive</a>
                                                    {{-- @endcan --}}
                                                    {{-- @can('archive bon') --}}
                                                    <a class="dropdown-item text-danger btn-sm"
                                                        data-bon_id="{{ $bonSortie->id }}"
                                                        data-toggle="modal"
                                                        data-target="#delete_bon"
                                                        href="#">Delete</a>
                                                    {{-- @endcan --}}
                                                    {{-- @can('print bon') --}}
                                                    <a class="dropdown-item text-primary btn-sm" 
                                                        href="{{route('print',$bonSortie->id)}}">Print</a>
                                                    {{-- @endcan --}}
												</div>
											</div>
										</td>                               
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- row closed -->
    <!-- Deleteing Model-->
    <div class="modal fade" id="delete_bon" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Suppression du bon</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('bonSorties.destroy',"test")}}" method="post">
                @method('DELETE')
                {{ csrf_field() }}
                <div class="modal-body">
                    <p class="text-center">
                    <h6 style="color:red">vous étes sure ?</h6>
                    </p>
                    
                    <input type="text" name="bon_id" id="bon_id" value="">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-danger">Confirmer</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- End Deleteing Model -->
<!-- Archiving Model-->
<div class="modal fade" id="archive_bon" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Suppression du bon</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('bonSorties.destroy',"test")}}" method="post">
                @method('DELETE')
                {{ csrf_field() }}
                <div class="modal-body">
                    <p class="text-center">
                    <h6 style="color:red">vous étes sure ?</h6>
                    </p>
                    <input type="text" name="page_id" id="page_id" value="2">
                    <input type="text" name="bon_id" id="bon_id" value="">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-danger">Confirmer</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- End Archiing Model -->
</div>
<!-- Container closed -->
</div>
<!-- main-content closed -->
@endsection
@section('js')
    <!-- Internal Data tables -->
    <script src="{{ URL::asset('assets/plugins/datatable/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/dataTables.dataTables.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/responsive.dataTables.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/jquery.dataTables.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/dataTables.bootstrap4.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/buttons.bootstrap4.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/jszip.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/pdfmake.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/vfs_fonts.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/buttons.html5.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/buttons.print.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/buttons.colVis.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ URL::asset('assets/plugins/datatable/js/responsive.bootstrap4.min.js') }}"></script>
    <!--Internal  Datatable js -->
    <script src="{{ URL::asset('assets/js/table-data.js') }}"></script>
    <!--Internal  Notify js -->
    <script src="{{URL::asset('assets/plugins/notify/js/notifIt.js')}}"></script>
    <script src="{{URL::asset('assets/plugins/notify/js/notifit-custom.js')}}"></script>




<script>
$('#delete_bon').on('show.bs.modal', function(event) {
    var button = $(event.relatedTarget)
    var bon_id = button.data('bon_id')
    var modal = $(this)
    modal.find('.modal-body #bon_id').val(bon_id);
})
</script>
<script>
$('#archive_bon').on('show.bs.modal', function(event) {
    var button = $(event.relatedTarget)
    var bon_id = button.data('bon_id')
    var modal = $(this)
    modal.find('.modal-body #bon_id').val(bon_id);
})
</script>
@endsection